namespace SharpChakra
{
   public enum JsErrorCode : uint
   {
      NoError = 0,
      CategoryUsage = 0x10000,
      InvalidArgument,
      NullArgument,
      NoCurrentContext,
      InExceptionState,
      NotImplemented,
      WrongThread,
      RuntimeInUse,
      BadSerializedScript,
      InDisabledState,
      CannotDisableExecution,
      HeapEnumInProgress,
      ArgumentNotObject,
      InProfileCallback,
      InThreadServiceCallback,
      CannotSerializeDebugScript,
      AlreadyDebuggingContext,
      AlreadyProfilingContext,
      IdleNotEnabled,
      CannotSetProjectionEnqueueCallback,
      CannotStartProjection,
      InObjectBeforeCollectCallback,
      ObjectNotInspectable,
      PropertyNotSymbol,
      PropertyNotString,
      CategoryEngine = 0x20000,
      OutOfMemory,
      CategoryScript = 0x30000,
      ScriptException,
      ScriptCompile,
      ScriptTerminated,
      ScriptEvalDisabled,
      CategoryFatal = 0x40000,
      Fatal,
      WrongRuntime,
   }
}
